### ISSUE TITLE
After installing zsh, latex-watcher not found

### ISSUE THREAD

**Issue by dnlrsr** [meltuhamy/latex-watcher#5]

**Comment by JuStTheDev** [comment]
@Dinodanio I think, this has to do with missing PATH variable in your .zshrc. I don't think, your problem is anyhow connectable to the source code of this project.
If I run `which latex-watcher` it says: `/home/jstrecker/.yarn/bin/latex-watcher`. This is the correct path to the executable. (Yes, I use yarn and not npm. It will look different on yours)
In my `~/.zshrc` I have this export statement (abridged):
```
export PATH="$HOME"/.local/bin:"$(yarn global bin)":"$PATH"
```
This adds the `yarn global bin` folder to the `PATH` variable and thus lets my system and (ohmy)zsh know, where latex-watcher is.

Hope I could help you. But still, this issue is not solvable by changing any code here.
